services:
  jbdetection_v1:
    container_name: jbdetection_v1
    build:
      context: ../..
      dockerfile: apps/backend/Dockerfile
    image: jbdetection-image-v1:${IMAGE_TAG:-latest}
    ports:
      - "5000:5000"
    volumes:
      - ./outputs_v1:/home/devio/JB-outputs
      - ./logs_v1:/home/devio/JB-logs
    environment:
      - PYTHONPATH=/app
    user: "1000:1000"  # <-- اضافه شد
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped
    command: >
      gunicorn apps.backend.app:app
        -b 0.0.0.0:5000
        --workers=2
        --threads=4
        --timeout=2700
        --max-requests=500
        --max-requests-jitter=50
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  jbdetection_v2:
    container_name: jbdetection_v2
    build:
      context: ../..
      dockerfile: apps/backend/Dockerfile
    image: jbdetection-image-v2:${IMAGE_TAG_V2:-test}
    ports:
      - "5001:5000"
    volumes:
      - ./outputs_v2:/home/devio/JB-outputs
      - ./logs_v2:/home/devio/JB-logs
    environment:
      - PYTHONPATH=/app
    user: "1000:1000"  # <-- اضافه شد
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped
    command: >
      gunicorn apps.backend.app:app
        -b 0.0.0.0:5001
        --workers=2
        --threads=4
        --timeout=2700
        --max-requests=500
        --max-requests-jitter=50
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
